#ifndef _U8G2_RTL_STRINGS_H_
#define _U8G2_RTL_STRINGS_H_

/*
 * Auto-generated by u8g2-rtl-strings
 *
 * Command:
 *   ./u8g2-rtl-strings.py -e rtl_test_128x128.c
 *
 * Input files:
 *   rtl_test_128x128.c
 *
 * Input files must be UTF-8 encoded.
 *
 * This header contains reshaped RTL strings
 * suitable for u8g2_DrawUTF8().
 *
 * DO NOT EDIT — changes will be overwritten.
 */

#define U8G2_RTL_OK(x) "\uFED6\uFED3\uFE8D\uFEEE\uFEE3" /* موافق */
#define U8G2_LEN_OK (5)
#define U8G2_RTL_CANCEL(x) "\uFE80\uFE8E\uFED0\uFEDF\uFE87" /* إلغاء */
#define U8G2_LEN_CANCEL (5)
#define U8G2_RTL_BACK(x) "\uFEC9\uFEEE\uFE9F\uFEAD" /* رجوع */
#define U8G2_LEN_BACK (4)
#define U8G2_RTL_NEXT(x) "\uFEF2\uFEDF\uFE8E\uFE98\uFEDF\uFE8D" /* التالي */
#define U8G2_LEN_NEXT (6)
#define U8G2_RTL_PREVIOUS(x) "\uFED6\uFE91\uFE8E\uFEB4\uFEDF\uFE8D" /* السابق */
#define U8G2_LEN_PREVIOUS (6)

#endif
