#!/usr/bin/env python3
#
# u8g2-rtl-strings
#
# Rewrite right-to-left strings backwards
#
# Extract U8G2_RTL_* macros from C source files, reshape RTL text,
# apply bidi reordering, and emit a C header file with the processed
# UTF-8 strings.
#
# Requirements:
#   arabic_reshaper
#   python-bidi
#
# Input files MUST be UTF-8 encoded.

import sys
import io
import re
import shlex
import argparse

import unicodedata
import arabic_reshaper
from bidi.algorithm import get_display

# Force UTF-8 stdout regardless of locale
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

macro_re = re.compile(
    r'U8G2_RTL_([A-Z0-9_]+)\s*\(\s*"((?:\\.|[^"\\])*)"\s*\)'
)


def process_string(text):
    reshaped = arabic_reshaper.reshape(text)
    return get_display(reshaped)


def emit_header_start(argv, files):
    print("#ifndef _U8G2_RTL_STRINGS_H_")
    print("#define _U8G2_RTL_STRINGS_H_")
    print()
    print("/*")
    print(" * Auto-generated by u8g2-rtl-strings")
    print(" *")
    print(" * Command:")
    print(" *   " + " ".join(shlex.quote(a) for a in argv))
    print(" *")
    print(" * Input files:")
    if files:
        for f in files:
            print(" *   " + f)
    else:
        print(" *   <stdin>")
    print(" *")
    print(" * Input files must be UTF-8 encoded.")
    print(" *")
    print(" * This header contains reshaped RTL strings")
    print(" * suitable for u8g2_DrawUTF8().")
    print(" *")
    print(" * DO NOT EDIT — changes will be overwritten.")
    print(" */")
    print()


def emit_header_end():
    print()
    print("#endif")


def process_stream(stream, filename, escape_mode = False):
    for lineno, line in enumerate(stream, 1):

        stripped = line.strip()

        # discard simple comment lines
        if stripped.startswith("//"):
            continue
        if stripped.startswith("/*"):
            continue

        m = macro_re.search(line)
        if not m:
            continue

        name = m.group(1)
        raw = m.group(2)

        visual = process_string(raw)

        #  ignore vowel marks in glyph_count
        glyph_count = sum(1 for c in visual if unicodedata.category(c) != 'Mn')

        macro = f"U8G2_RTL_{name}"

        if escape_mode:
            escaped = ''.join(f'\\u{ord(c):04X}' for c in visual)
            print(f'#define {macro}(x) "{escaped}" /* {raw} */')
        else:
            print(f'#define {macro}(x) "{visual}" /* {raw} */')

        print(f'#define U8G2_LEN_{name} ({glyph_count})')

def main():

    parser = argparse.ArgumentParser(
        description='Extract and reshape right-to-left strings for u8g2',
        epilog='Output is written to stdout as a C header file.'
    )
    parser.add_argument('files', nargs='*', 
                       help='Input C files (if none, read from stdin)')
    parser.add_argument('-e', '--escape', action='store_true',
                       help='Output Unicode escape sequences (\\uXXXX) instead of raw UTF-8')
    
    args = parser.parse_args()
    files = args.files
    escape_mode = args.escape

    emit_header_start(sys.argv, files)

    if files:
        for f in files:
            try:
                with open(f, "r", encoding="utf-8") as fp:
                    process_stream(fp, f, escape_mode)
            except UnicodeDecodeError:
                print(f"{f}: error: file is not UTF-8", file=sys.stderr)
            except FileNotFoundError:
                print(f"{f}: error: file not found", file=sys.stderr)

    else:
        process_stream(sys.stdin, "<stdin>")

    emit_header_end()


if __name__ == "__main__":
    main()
