/* Generated by hbpp.py — do not edit manually */
/* Source:  mui_form_en.c */
/* Command: tools/hbpp/hbpp.py font/unifont-17.0.04.otf 16 applications/u8g2/mui_form_en.c applications/u8g2/mui_hb_strings.h */

#ifndef MUI_HB_STRINGS_H
#define MUI_HB_STRINGS_H

#include <stdint.h>

// न म स ् त े
static const uint8_t _hb_NAMASTE_data[] U8X8_PROGMEM = {
  0x09, 0x28, 0x00, 0x00,  // 'U+0928'
  0x09, 0x2e, 0x10, 0x00,  // 'U+092E'
  0x09, 0x38, 0x10, 0x00,  // 'U+0938'
  0x09, 0x4d, 0x00, 0x00,  // 'U+094D'
  0x09, 0x24, 0x10, 0x00,  // 'U+0924'
  0x09, 0x47, 0x00, 0x00,  // 'U+0947'
  0x00, 0x00  // end
};
static const uint8_t *mui_hb_strings_strings[] = {
    _hb_NAMASTE_data,  /* 0 */
};

#define MUI_XYHB_NAMASTE(id, x, y, s)  "A" "HB" "\x00" "\x5f" "\x00"

/*
 * MUI callback — implement once in your project:
 *
 *   MUIF_RO("HB", mui_draw_hb)
 *
 *   uint8_t mui_draw_hb(mui_t *ui, uint8_t msg) {
 *       if (msg == MUIF_MSG_DRAW)
 *           u8g2_DrawHB(mui_get_U8g2(ui), ui->x, ui->y,
 *                       mui_hb_strings_strings[ui->arg]);
 *       return 0;
 *   }
 */

#endif /* MUI_HB_STRINGS_H */
