#ifndef _U8G2_RTL_STRINGS_H_
#define _U8G2_RTL_STRINGS_H_

/*
 * Auto-generated by u8g2-rtl-strings
 *
 * Command:
 *   tools/u8g2-rtl-strings/u8g2-rtl-strings.py applications/u8g2/mui_form_en.c
 *
 * Input files:
 *   applications/u8g2/mui_form_en.c
 *
 * Input files must be UTF-8 encoded.
 *
 * This header contains reshaped RTL strings
 * suitable for u8g2_DrawUTF8().
 *
 * DO NOT EDIT — changes will be overwritten.
 */

#define U8G2_RTL_HELLO(x) "ﻡﻼﺳ" /* سلام */
#define U8G2_LEN_HELLO (3)

#endif
