#!/bin/bash -x
# build .uf2 firmware from the shell prompt
# for local toolchain on linux
CURRENT_UF2=/media/$USER/CherryUF2/CURRENT.UF2
#scons -c
scons
# extract binary from elf
arm-none-eabi-objcopy -O binary rtthread.elf rtthread.bin
# at32f405 running in external qspi flash - uf2 family id 0xf35c900d load address 0x90000000
# convert to uf2 format
./tools/uf2conv/uf2conv.py -c -b 0x90000000 -f 0xf35c900d -o rtthread.uf2 rtthread.bin
# flash
if [ -e rtthread.uf2 -a -e $CURRENT_UF2 ]
then
  cp rtthread.uf2 $CURRENT_UF2
fi
