# workflow to build and release firmware for arm_can_tool
# creates .uf2 binary
# loosely based upon rt-thread bsp_buildings workflow

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Publish a GitHub release from this build'
        type: boolean
        default: false

name: arm_can_tool

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: build arm_can_tool
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: checkout arm_can_tool sources
        uses: actions/checkout@v7

      - name: docker build
        run: docker build --target build -t arm_can_tool -f tools/docker/Dockerfile .

      - name: extract firmware
        run: |
          id=$(docker create arm_can_tool)
          docker cp "$id":/output ~/arm_can_tool_firmware
          docker rm "$id"

      - name: upload firmware
        uses: actions/upload-artifact@v7
        with:
          name: arm_can_tool_firmware
          path: ~/arm_can_tool_firmware
          retention-days: 1

  release:
    name: release arm_can_tool
    runs-on: ubuntu-22.04
    needs: build
    if: ${{ inputs.release }}
    timeout-minutes: 5
    permissions:
      contents: write
    steps:

      - name: download firmware
        uses: actions/download-artifact@v8
        with:
          name: arm_can_tool_firmware
          path: artifacts

      - name: set short sha
        id: vars
        run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/*"
          body: "arm_can_tool firmware, built from ${{ steps.vars.outputs.short_sha }}"
          tag: build-${{ github.run_number }}
          commit: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

# not truncated
